# Notation header (see NOTATION.md):
# signature (+---); Y = g^mn d_m Phi d_n Phi; B^AB = -g^mn d_m phi^A d_n phi^B.
# T_mn = 2*dL/dg^mn - g_mn*L; off-diagonal symmetric variables use factor 1.
# Horndeski/EFT bridge only: X = -1/2 g^mn d_m Phi d_n Phi, so Y = -2X.

"""
PHASE 38: Z9 reduced-holonomy candidate for theta = 2/9

Status:
    Candidate derivation, not yet a theorem from the full RFG action.

Goal:
    Explain why the C3 Koide operator of phase37 should use

        theta = 2/9

    without fitting theta to the charged-lepton masses.

Core idea:
    The lepton oscillon is not just a three-axis object. It is a framed
    C3-cyclic defect. The internal return map therefore has two discrete
    factors:

        1. three spatial/director axes:        C3
        2. three cyclic phase/braid sectors:   C3

    The combined closure lattice has

        N_closure = 3 * 3 = 9

    elementary reduced-holonomy slots.

    A charged lepton is fermionic/Mobius-like, so the frame cannot close
    by the trivial single-cover branch. The minimal non-trivial oriented
    framed closure index is

        h_framed = 2.

    The reduced elastic holonomy angle entering the C3 stiffness operator is

        theta = h_framed / N_closure = 2 / 9.

Action-level support:
    phase39_action_symmetry_to_z9.py derives the two C3 factors from
    the oriented elastic triad and the triaxial strain doublet:

        S3 -> A3 ~= C3,
        E -> omega^2 E, so E^3 is the first phase-sensitive invariant.

Spinorial/framed support:
    phase40_projective_spinor_h2.py explains why h=1 is only a
    projective/nematic closure (n -> -n), while h=2 is the first
    non-trivial oriented framed closure required by the charged sector.

Normal-form support:
    phase41_action_normal_form_theta.py shows that the C3 strain-sector
    lock is generated by the existing action invariant I3=det(B):
    E^3 + Ebar^3 = 27 det(Q).

Interpretation:
    This is not a usual U(1) phase measured modulo 2*pi. It is a reduced
    director/framing holonomy measured in the internal elastic normal-form
    coordinate. A periodic version can be written as

        V_lock(theta) = kappa * [1 - cos(pi * (9 theta - 2))]

    whose first oriented framed minimum is theta = 2/9.

Why this matters:
    phase37 showed that theta = 2/9 gives the charged-lepton frequency
    ratios 1 : 14.37951 : 58.97010 and exact Koide structure. This file
    gives a discrete, no-continuous-parameter route to that theta.
"""

import math

from phase37_c3_koide_operator import (
    THETA_TOPOLOGICAL,
    c3_frequency_ratios,
    c3_mass_predictions,
    koide_identity,
    prediction_table,
)


AXIS_CYCLE_ORDER = 3
PHASE_BRAID_ORDER = 3
SPINOR_CLOSURE_INDEX = 2


def closure_lattice_order():
    """Combined C3(axis) x C3(phase/braid) reduced closure count."""
    return AXIS_CYCLE_ORDER * PHASE_BRAID_ORDER


def theta_from_z9_holonomy(
    spinor_index=SPINOR_CLOSURE_INDEX,
    axis_order=AXIS_CYCLE_ORDER,
    phase_order=PHASE_BRAID_ORDER,
):
    """Reduced holonomy angle theta = h / (axis_order * phase_order)."""
    return spinor_index / (axis_order * phase_order)


def locking_potential(theta, kappa=1.0):
    """
    Periodic reduced-framing lock:

        V = kappa * [1 - cos(pi * (9 theta - 2))]

    The pi appears because the reduced director/framing coordinate is
    measured in half-turn units. Minima occur at 9 theta - 2 = 2 n.
    The first oriented framed branch is theta = 2/9.
    """
    return kappa * (1.0 - math.cos(math.pi * (closure_lattice_order() * theta - SPINOR_CLOSURE_INDEX)))


def locking_gradient(theta, kappa=1.0):
    """Derivative of locking_potential with respect to theta."""
    n = closure_lattice_order()
    return kappa * math.pi * n * math.sin(math.pi * (n * theta - SPINOR_CLOSURE_INDEX))


def locking_curvature(theta, kappa=1.0):
    """Second derivative of locking_potential with respect to theta."""
    n = closure_lattice_order()
    return kappa * (math.pi * n) ** 2 * math.cos(math.pi * (n * theta - SPINOR_CLOSURE_INDEX))


def positivity_edge_for_c3_operator():
    """
    The smallest C3 eigenfrequency hits zero when

        1 + sqrt(2) cos(theta + 2*pi/3) = 0.

    On the small positive branch this gives theta = pi/12.
    """
    return math.pi / 12.0


def branch_audit(max_index=5):
    """
    Enumerate theta = h/9 branches and test basic C3-spectrum viability.

    Even h is the oriented framed closure family in this candidate map.
    h=2 is the first non-trivial even branch below the positivity edge.
    """
    n = closure_lattice_order()
    edge = positivity_edge_for_c3_operator()
    rows = []
    for h in range(max_index + 1):
        theta = h / n
        raw = [
            1.0 + math.sqrt(2.0) * math.cos(theta + 2.0 * math.pi * k / 3.0)
            for k in range(3)
        ]
        positive = all(value > 0.0 for value in raw)
        oriented_framed = (h % 2 == 0 and h != 0)
        candidate = (h == SPINOR_CLOSURE_INDEX)
        ratios = None
        if positive:
            values = sorted(raw)
            ratios = [value / values[0] for value in values]
        rows.append(
            {
                "h": h,
                "theta": theta,
                "theta_less_than_edge": theta < edge,
                "positive_spectrum": positive,
                "oriented_framed_branch": oriented_framed,
                "selected_candidate": candidate,
                "frequency_ratios": ratios,
            }
        )
    return rows


def derivation_summary():
    """Compact statement of the candidate derivation."""
    n = closure_lattice_order()
    theta = theta_from_z9_holonomy()
    edge = positivity_edge_for_c3_operator()
    return {
        "axis_cycle_order": AXIS_CYCLE_ORDER,
        "phase_braid_order": PHASE_BRAID_ORDER,
        "closure_lattice": f"{AXIS_CYCLE_ORDER} x {PHASE_BRAID_ORDER} = {n}",
        "oriented_framed_index": SPINOR_CLOSURE_INDEX,
        "theta": theta,
        "theta_phase37_constant": THETA_TOPOLOGICAL,
        "matches_phase37": abs(theta - THETA_TOPOLOGICAL) < 1.0e-15,
        "positivity_edge": edge,
        "below_edge": theta < edge,
        "locking_gradient": locking_gradient(theta),
        "locking_curvature": locking_curvature(theta),
        "status": "Candidate derivation; phase39 gives C3xC3, phase40 gives h=2, phase41 gives action C3 lock.",
    }


def falsification_targets():
    """
    What would make this candidate fail.
    """
    return [
        "If the lepton oscillon is not C3-cyclic, N_closure=9 collapses.",
        "If the charged sector does not require oriented framed closure, h=2 is not selected.",
        "If the elastic operator uses the full U(1) phase directly, theta should be 2*pi/9, which fails the masses.",
        "If h=1 is shown to be a valid oriented charged branch rather than projective/nematic only, the uniqueness of h=2 fails.",
        "If the RFG action cannot generate the reduced-framing lock V ~ 1 - cos(pi(9 theta - 2)), this remains numerology.",
    ]


if __name__ == "__main__":
    print("=" * 72)
    print("PHASE 38: Z9 reduced-holonomy candidate for theta = 2/9")
    print("=" * 72)

    print("\n1. Discrete closure derivation")
    summary = derivation_summary()
    for key, value in summary.items():
        if isinstance(value, float):
            print(f"  {key:24s}: {value:.12g}")
        else:
            print(f"  {key:24s}: {value}")

    print("\n2. Branch audit theta = h/9")
    for row in branch_audit():
        ratios = row["frequency_ratios"]
        if ratios is None:
            ratio_text = "not physical"
        else:
            ratio_text = " : ".join(f"{value:.5g}" for value in ratios)
        marker = " <-- selected" if row["selected_candidate"] else ""
        print(
            f"  h={row['h']} theta={row['theta']:.9f} "
            f"positive={row['positive_spectrum']} "
            f"oriented={row['oriented_framed_branch']} "
            f"ratios={ratio_text}{marker}"
        )

    print("\n3. Charged-lepton prediction inherited from phase37")
    print(f"  K_C3 = {koide_identity():.12f}")
    for row in prediction_table():
        print(
            f"  {row['particle']:8s}: "
            f"nu_C3={row['predicted_freq_ratio']:.8f}, "
            f"m_C3={row['predicted_mass_MeV']:.6f} MeV, "
            f"m_obs={row['observed_mass_MeV']:.6f} MeV, "
            f"rel_err={row['relative_mass_error']:.3e}"
        )

    print("\n4. Falsification targets")
    for item in falsification_targets():
        print(f"  - {item}")
